### ISSUE TITLE
Issue when removing item

### ISSUE THREAD

**Issue by Vincz** [jaredLunde/masonic#12]
**Describe the bug**
Hey Jared :) I found an issue when we remove element from the items list. If there is a lot of items, it seems to work. But if the list is small, we get an error. 

**To Reproduce**
I made a sandbox to reproduce : https://codesandbox.io/s/masonic-example-lpe8s
Just click on the button "Remove a cat"
If you change the number of cat to 200 for example, it works.
With 20 cats, it failed with the following error:

```
TypeError
Invalid value used as weak map key
s2
https://lpe8s.csb.app/node_modules/trie-memoize/dist/main/index.js:65:14
eval
https://lpe8s.csb.app/node_modules/trie-memoize/dist/main/index.js:92:9
eval
https://lpe8s.csb.app/node_modules/masonic/dist/main/index.js:131:11
eval
https://lpe8s.csb.app/node_modules/masonic/dist/main/index.js:796:9
Object.search
https://lpe8s.csb.app/node_modules/masonic/dist/main/IntervalTree.js:374:35
range
https://lpe8s.csb.app/node_modules/masonic/dist/main/index.js:795:20

```

**Comment by jaredLunde** [comment]
This is the expected behavior, though I need to it document it better. This is the same problem solved by:

- https://codesandbox.io/s/masonic-w-react-router-example-2b5f9?file=/src/index.js
- https://codesandbox.io/s/masonic-w-react-router-and-advanced-config-example-8em42?file=/src/index.js

When you change your items list you are responsible for resetting the positioner. The reason for this is Masonic can't make assumptions about changes to the items array, since people could be using a list this mutable or immutable, that gets longer over time, etc.

**Comment by jaredLunde** [comment]
I should maybe throw a specific error in dev, too, if the items list gets shorter but the positioner doesn't change. Will have to explore that.

**Comment by renanbgarcia** [comment]
Should it work with the useMasonry() hook too?
I've been trying but it's still not working when the items array size change.

https://codesandbox.io/s/usemasonry-example-gvf4b

**Comment by jaredLunde** [comment]
@renanbgarcia Numerous problems in your example, but at the end of the day it's just not a good idea to do this. It's rather out of the scope of the library. Firstly, you're unlikely to get the kind of behavior you're looking for. No matter what, you're going to have to trigger a reflow on the entire grid, which means when a user deletes an item they'll end up back at the beginning of the grid each time it happens. You're much better off doing something else with the card when it's been deleted like inserting a placeholder letting a user know it was deleted. The primary objective of this library is to create masonry grids in an algorithmically-sound way. A secondary objective is keeping the hit to the bundle size low. Neither of those two things really mesh with this capability. There might be a day when I revisit this, but it's not on the current roadmap.

**Comment by khmm12** [comment]
@jaredLunde 

In that case `usePositioner` should recreate positioner instance before masonic render when deps has been changed ;-).

https://github.com/jaredLunde/masonic/blob/6fca86900ffa306a40b99dd0d49b69a9160b34b5/src/use-positioner.ts#L42

What happens now:

1. The items list has been changed;
2. `usePositioner` schedules effect after component render;
3. `useMasonic` renders items using **stale** positioner instance;
4. React executes the scheduled effect, a new positioner is created;
5. `useMasonic` renders items using the new positioner instance.

I think it's clear what will happen on 3 step if the items list becomes shorter.

It should be something like that:

```ts
type UsePositionerState = {
  deps: React.DependencyList
  positioner: Positioner
}

const [state, setState] = useState<UsePositionerState>(() => {
  const positioner = initPositioner()
  return {
    deps,
    positioner
  }
})

let { deps: previousDeps, positioner } = state

const hasDepsChanged = !isEqual(previousDeps, deps)
if (hasDepsChanged) {
  const newPositioner = initPositioner()
  positioner = newPositioner
  previousDeps = deps

  setState({ deps, positioner })
}
```

It will guarantee new positioner instance during the same render.

**Comment by y0zhyk** [comment]
@jaredLunde, @khmm12 I don't think the issue it completely fixed. I continue to see the issue even after upgrade to v3.3.10.

**Comment by jaredLunde** [comment]
@y0zhyk post a reproduction on codesandbox please

**Comment by JhonJohnatan** [comment]
I agree. it didn't fixed.

**Comment by khmm12** [comment]
@y0zhyk @JhonJohnatan Could you share an example? It's hard to say anything helpful without code.

I have some assumptions, but it's better to see the example at first.

**Comment by cryptoAlgorithm** [comment]
@khmm12 I've noticed the same issue even after updating to the latest version. I've forked the codesandbox example in the first post and updated Masonic to the latest version, but I receive the error 

```
No data was found at index: 19

This usually happens when you've mutated or changed the "items" array in a way that makes it shorter than the previous "items" array. Masonic knows nothing about your underlying data and when it caches cell positions, it assumes you aren't mutating the underlying "items".

See https://codesandbox.io/s/masonic-w-react-router-example-2b5f9?file=/src/index.js for an example that gets around this limitations. For advanced implementations, see https://codesandbox.io/s/masonic-w-react-router-and-advanced-config-example-8em42?file=/src/index.js

If this was the result of your removing an item from your "items", see this issue: https://github.com/jaredLunde/masonic/issues/12
```

https://user-images.githubusercontent.com/64193267/118508389-bd441b00-b761-11eb-9076-6f234269e21f.mov

Here's the forked codesandbox: https://codesandbox.io/s/masonic-example-forked-hcz62

**Comment by sebyx07** [comment]
@cryptoAlgorithm you can try the following thing:
when you delete a item item, you don't really remove it, just set a property like `.__to_be_removed__ = true`
then in you render FakeCard

```js
if(__to_be_removed__) return null
```

not pretty, but works

**Comment by khmm12** [comment]
@cryptoAlgorithm 

The same example but using masonic hooks directly. 
https://codesandbox.io/s/masonic-example-forked-18nu4?file=/src/index.js

The key difference is `usePositioner`'s dependency.

```js
  const positioner = usePositioner(
    { width, columnGutter: 8, columnWidth: 172 },
    [cats.length]
  );
```

You should tell positioner about collection size changes. 

May it makes sense to add `items` as `usePositioner`'s dependency inside `Masonic` component. 

@jaredLunde what do you think?

**Comment by cryptoAlgorithm** [comment]
@sebyx07 good suggestion, but I'm sure there'll be issues managing 10k+ items with a few thousand more deleted items...

@khmm12 this solution seems to be promision. I'll impliment it when I have the time. I was using a hack previously to essentially reinitialise masonic every time the length of the data changes (yes, very inefficient)

**Comment by mattandersonfg** [comment]
@khmm12 how would you solve this issue happening when a masonic <List /> is in use? `usePositioner` is not an option there.

**Comment by khmm12** [comment]
@mattandersonfg in this case `key` is rescue (with some downsides), but I would go with [`useMasonry`](https://github.com/jaredLunde/masonic#usemasonryoptions). 

Personally I don't see any problem to use hooks directly or create your component using these hooks. `Masonry` and `List` components do nothing special. 

P.S. I don't want to be "Devil's advocate". IMO `Masonry` component should include items.length as `usePositioner` dependency, because it's some kind of "black-box" which should work out-of-box by its definition.

**Comment by mattandersonfg** [comment]
@khmm12 I'm providing both a `key` and `itemKey` to the List, but I need to be able to delete items from the list. On deletion there's an "Invalid value used as weak map key" error.

**Comment by rockhentai** [comment]
same problem

**Comment by gadicc** [comment]
Ugly But It Works™:

Copy of https://github.com/jaredLunde/masonic/blob/main/src/masonry.tsx with additions:

```diff
+  // Workaround for https://github.com/jaredLunde/masonic/issues/12
+  const itemCounter = React.useRef<number>(props.items.length);
+  let shrunk = false;
+  if (props.items.length !== itemCounter.current) {
+    if (props.items.length < itemCounter.current) shrunk = true;
+    itemCounter.current = props.items.length;
+  }
+
- nextProps.positioner = usePositioner(nextProps);
+ nextProps.positioner = usePositioner(nextProps, [shrunk && Math.random()]);
```

**Comment by kostia-official** [comment]
Will post my quick workaround for Masonry component. After detecting an item remove I increment removesCount that goes to grid key and rerenders grid.

  ```js
    const itemsCount = items?.length;
    const prevItemsCount = usePrevious(itemsCount);

    const removesCount = useRef(0);

    const gridKeyPostfix = useMemo(() => {
      if (!itemsCount || !prevItemsCount) return removesCount.current;
      if (itemsCount < prevItemsCount) {
        removesCount.current += 1;
        return removesCount.current;
      }

      return removesCount.current;
    }, [itemsCount, prevItemsCount]);

        <Masonry
          key={`${gridKey}-${gridKeyPostfix}`}
```

**Comment by flnx** [comment]
> Ugly But It Works™:
> 
> Copy of https://github.com/jaredLunde/masonic/blob/main/src/masonry.tsx with additions:
> 
> ```diff
> +  // Workaround for https://github.com/jaredLunde/masonic/issues/12
> +  const itemCounter = React.useRef<number>(props.items.length);
> +  let shrunk = false;
> +  if (props.items.length !== itemCounter.current) {
> +    if (props.items.length < itemCounter.current) shrunk = true;
> +    itemCounter.current = props.items.length;
> +  }
> +
> - nextProps.positioner = usePositioner(nextProps);
> + nextProps.positioner = usePositioner(nextProps, [shrunk && Math.random()]);
> ```
> 
> We only update on a _smaller_ array because otherwise there is flicker (e.g. on more items coming in from infinite scroll). Make sure you `key` and `itemKey` are set too (as per comments above).

This helped a lot. I was trying to get around with that flickering for a while. Thanks!

**Comment by zspitz** [comment]
> Ugly But It Works™:
> 
> Copy of https://github.com/jaredLunde/masonic/blob/main/src/masonry.tsx with additions:
> 
> ```diff
> +  // Workaround for https://github.com/jaredLunde/masonic/issues/12
> +  const itemCounter = React.useRef<number>(props.items.length);
> +  let shrunk = false;
> +  if (props.items.length !== itemCounter.current) {
> +    if (props.items.length < itemCounter.current) shrunk = true;
> +    itemCounter.current = props.items.length;
> +  }
> +
> - nextProps.positioner = usePositioner(nextProps);
> + nextProps.positioner = usePositioner(nextProps, [shrunk && Math.random()]);
> ```

@gadicc why do you need `Math.random()`?

```
const lengthRef = useRef(0) 
// ...
const positioner = usePositioner(
    { width, columnWidth, columnGutter },
    [cards.length < lengthRef.current]
)
// ...
lengthRef.current = items.length
```

**Comment by ssonit** [comment]
> Will post my quick workaround for Masonry component. After detecting an item remove I increment removesCount that goes to grid key and rerenders grid.
> 
> ```js
>   const itemsCount = items?.length;
>   const prevItemsCount = usePrevious(itemsCount);
> 
>   const removesCount = useRef(0);
> 
>   const gridKeyPostfix = useMemo(() => {
>     if (!itemsCount || !prevItemsCount) return removesCount.current;
>     if (itemsCount < prevItemsCount) {
>       removesCount.current += 1;
>       return removesCount.current;
>     }
> 
>     return removesCount.current;
>   }, [itemsCount, prevItemsCount]);
> 
>       <Masonry
>         key={`${gridKey}-${gridKeyPostfix}`}
> ```

thanks so much, i fixed it

**Comment by JulianKominovic** [comment]
Hi! I found two main issues with the previous approach:
- Performance issues by changing the Masonry component key when an item updates
- Tracking items length only works when deleting or adding an items but doesn't play well with updates on existing items

So I ended up with something like this:
```jsx
 <Masonry
      columnGutter={16}
      columnWidth={300}
      items={items}
      render={Renderer}
      // This does the trick
      itemKey={(item, index) => index + item.id + item.updatedAt}
    />
```

I've been tunning the itemKey to cover my needs and prevent cards for taking wrong places in the masonry or calculating the wrong height.
Hope it helps!

_BTW I love this lib, KUDOS to the team behind ❤_

**Comment by Norlandz** [comment]
<strike>What is the correct solution currently? 
Even if I give it a distinct key to manually remount it, it some how just finds a way to render itself and knowing the array have item removed and complains. 
Unless I randomly give it a key in every single render, which cause it to keep going to the bottom and keeps infinite refetching from my query.</strike>

---

Ok got it worked:

https://github.com/jaredLunde/masonic/issues/12#issuecomment-2089843741

> Will post my quick workaround for Masonry component. After detecting an item remove I increment removesCount that goes to grid key and rerenders grid.
> ```ts
>   const itemsCount = items?.length;
>   const prevItemsCount = usePrevious(itemsCount);
> 
>   const removesCount = useRef(0);
> 
>   const gridKeyPostfix = useMemo(() => {
>     if (!itemsCount || !prevItemsCount) return removesCount.current;
>     if (itemsCount < prevItemsCount) {
>       removesCount.current += 1;
>       return removesCount.current;
>     }
> 
>     return removesCount.current;
>   }, [itemsCount, prevItemsCount]);
> 
>       <Masonry
>         key={`${gridKey}-${gridKeyPostfix}`}
> ```


I made a change to `if (prevItemsCount === undefined) return removesCount.current;` 
because you may have `0`
and `!0` is not triggering the increment of key.


```ts

import { usePrevious, usePreviousDistinct } from 'react-use';

...

const MasonryHolder = React.memo<{
  rows: ArticleBrief[];
}>(({ rows }) => {
  //   const [masonryLayoutIdBugFix, set_masonryLayoutIdBugFix] = useState(0);
  //
  //   const changed = prevItemsCount !== itemsCount;

  // useEffect(() => {
  //   set_masonryLayoutIdBugFix((masonryLayoutIdBugFix_prev) => masonryLayoutIdBugFix_prev + 1);
  // }, [data]);

  // remountMasonryWhenListRemoveAnItem
  // useEffect(() => {
  //   set_masonryLayoutIdBugFix((masonryLayoutIdBugFix_prev) => masonryLayoutIdBugFix_prev + 1);
  // }, [data]);

  //   const [shouldTriggerRemount, setShouldTriggerRemount] = useState(false);
  //   const [remountKey, setRemountKey] = useState(0);
  //   useEffect(() => {
  //     if (shouldTriggerRemount) {
  //       setRemountKey((prevKey) => prevKey + 1);
  //     }
  //   }, [shouldTriggerRemount]);
  //
  //   useEffect(() => {
  //     setShouldTriggerRemount((prev) => !prev);
  //   }, [data]);

  //   const largestArrayLength = useRef(rows.length);
  //
  //   const lengthPreservingArray = useMemo(() => {
  //     if (rows.length > largestArrayLength.current) {
  //       largestArrayLength.current = rows.length;
  //     }
  //     return Array.from({ length: largestArrayLength.current }, (_, i) => rows[i] ?? {});
  //   }, [rows]);

  const itemsCount = rows.length;
  const prevItemsCount = usePrevious(itemsCount); // @bug somehow its getting the same value as itemsCount // idk is due to the isLoading thus double render or what
  const removesCount = useRef(0);
  const gridKeyPostfix = useMemo(() => {
    // console.log('itemsCount', itemsCount, 'prevItemsCount', prevItemsCount, 'removesCount', removesCount.current);
    if (prevItemsCount === undefined) return removesCount.current;
    if (itemsCount < prevItemsCount) {
      removesCount.current += 1;
      return removesCount.current;
    }
    return removesCount.current;
  }, [itemsCount, prevItemsCount]);

  return (
    <Masonry
      // key={remountKey}
      key={gridKeyPostfix}
      items={rows}
      // items={lengthPreservingArray}
      columnGutter={16}
      columnCount={3}
      render={MasonryCard}
      // Turn off virtualisation · Issue #56 · jaredLunde/masonic
      // https://github.com/jaredLunde/masonic/issues/56
      // overscanBy={Infinity}
      itemHeightEstimate={700}
      // item can be undefined?...
      itemKey={(item, index) => index + '-' + item?.id}
    />
  );
});
const MasonryCard = React.memo<{
  index: number;
  data: ArticleBrief;
  width: number;
}>((props) => {
  const { index, data: articleBrief, width } = props;
  return <ArticleBriefCellPanel key={articleBrief.id} articleBrief={articleBrief} width={width} />;
});

```
